package com.jiesa.xvideocatcher.hook

import android.app.Activity
import android.content.Context
import android.widget.Toast
import com.jiesa.xvideocatcher.DiagLog
import de.robv.android.xposed.XC_MethodHook
import de.robv.android.xposed.XposedBridge
import de.robv.android.xposed.XposedHelpers
import java.lang.reflect.Modifier

/**
 * Adds a download entry to X's share sheet, in X's process.
 *
 * How the entry gets there: the sheet controller builds its item list, then calls its show method
 * to display it. Hooking that show method means appending one item to a list that is about to be
 * rendered — no view inflation, no layout inspection, no window of our own. The entry looks native
 * because it *is* native; only its contents come from us.
 *
 * How the click is caught: rather than hooking a click listener (whose class is obfuscated and,
 * unlike the item model, has no stable string anchor left in X 12.13), the injected item is given
 * a sentinel action id. Any item dispatched with that id is ours. That trades a fragile lookup for
 * a value we control.
 *
 * Failure policy: every hook body is wrapped. A throw inside a host UI callback would surface to
 * the user as X crashing, which is a worse outcome than a missing download entry.
 */
internal class ShareSheetInjector(
    private val classLoader: ClassLoader,
    private val moduleResources: ModuleStrings,
    private val onDownload: (Context, Any) -> Unit,
) {

    /**
     * Action id carried by the injected entry.
     *
     * Chosen far outside the host's own id space, which is generated by its resource compiler and
     * lives in low ranges. A collision would mean X's own handler runs for our entry.
     */
    private val sentinelActionId = 0x5EED_0001

    fun install() {
        // Resolved by shape, not by the recorded name. In 12.13.0-release.0 the recorded
        // controller name (`…legacy.h0`, read from 12.13.0-beta.0) loads successfully but is an
        // unrelated 1-field class, so a name-only lookup reported "resolved" and then failed to
        // find the show method. See HostResolver.
        val controller = HostResolver.shareSheetController(classLoader)
        if (controller == null) {
            DiagLog.flushNow()
            XposedBridge.log("XVC: share sheet controller not found; entry not installed")
            return
        }
        DiagLog.line("share sheet controller resolved: ${controller.cls.name}")

        hookSheetShown(controller)
        hookItemDispatch(controller.cls)
    }

    /** Appends the download entry to the item list right before the sheet is shown. */
    private fun hookSheetShown(controller: HostResolver.Controller) {
        DiagLog.line("hooked show method ${controller.showMethod.name}(FragmentManager)")

        XposedBridge.hookMethod(controller.showMethod, object : XC_MethodHook() {
            override fun beforeHookedMethod(param: MethodHookParam) {
                runCatching { appendEntry(param.thisObject) }
                    .onFailure {
                        DiagLog.line("ERROR append failed: $it")
                        XposedBridge.log("XVC: append failed: $it")
                    }
            }
        })
    }

    /**
     * Appends the entry, reporting which step failed when it does not appear.
     *
     * Every early return here is a different reason for the same visible symptom - the sheet opens
     * without a download entry. Returning silently made those five causes indistinguishable, so
     * each one names itself in the diagnostic log. This runs once per sheet open, not on any hot
     * path, so the logging costs nothing measurable.
     */
    private fun appendEntry(sheet: Any) {
        val tweet = tweetOf(sheet)
        if (tweet == null) {
            DiagLog.line("sheet opened: tweet field not found on ${sheet.javaClass.name}")
            return
        }

        val media = TweetMedia.extract(tweet)
        if (media.isEmpty()) {
            // Expected on a text-only post. Logged anyway: "video post shows no entry" and
            // "text post shows no entry" are the same symptom and need telling apart.
            DiagLog.line("sheet opened: no downloadable media found in tweet")
            return
        }
        DiagLog.line("sheet opened: ${media.size} downloadable item(s)")

        val itemsField = itemsFieldOf(sheet.javaClass)
        if (itemsField == null) {
            DiagLog.line("ENTRY SKIPPED: item list field not found on ${sheet.javaClass.name}")
            return
        }
        val current = itemsField.get(sheet) as? List<*>
        if (current == null) {
            DiagLog.line("ENTRY SKIPPED: item list field held ${itemsField.get(sheet)?.javaClass?.name}")
            return
        }
        if (current.any { it != null && isOurEntry(it) }) {
            // Not a failure: some screens rebuild the sheet, others reuse it.
            return
        }

        val entry = buildEntry(sheet)
        if (entry == null) {
            DiagLog.line("ENTRY SKIPPED: could not construct a host item (${HostClasses.ACTION_SHEET_ITEM})")
            return
        }
        itemsField.set(sheet, current.filterNotNull() + entry)
        DiagLog.line("entry added to sheet (${current.size} host items)")
    }

    /**
     * Builds an item of the host's own item type.
     *
     * The host renders its list by reading fields off these objects, so an entry has to *be* one
     * of them; a look-alike of our own class would be cast-failed or skipped. The 3-arg
     * constructor `(drawableRes, actionId, title)` is the minimal shape that produces a complete
     * row, and it is present in every build examined.
     */
    private fun buildEntry(sheet: Any): Any? {
        val itemClass = HostResolver.actionSheetItem(classLoader) ?: return null
        val ctor = HostResolver.entryConstructor(itemClass) ?: return null

        val title = moduleResources.downloadLabel(hostContext(sheet))
        // Icon 0 = no icon. Referencing one of X's own drawables would look tidier but ties the
        // entry to a resource id that is regenerated on every host build.
        return runCatching { ctor.newInstance(0, sentinelActionId, title) }.getOrNull()
    }

    /**
     * Watches item dispatch for the sentinel id.
     *
     * Which method receives the chosen item is not knowable by name, so it is selected by
     * signature: takes exactly one argument, and that argument is the host's item type. Hooking
     * every one-argument method instead would put this check on the path of unrelated host calls
     * — measurable on low-end hardware, for no gain.
     */
    private fun hookItemDispatch(controller: Class<*>) {
        val itemClass = HostResolver.actionSheetItem(classLoader)
        val single = controller.declaredMethods.filter {
            !Modifier.isStatic(it.modifiers) && it.parameterTypes.size == 1
        }

        // Prefer methods typed to the item class itself. `isAssignableFrom` is deliberately not
        // used for the primary pass: every class is assignable to Object, so it would match any
        // one-argument method and defeat the narrowing.
        var candidates = single.filter { m ->
            val p = m.parameterTypes[0]
            if (itemClass != null) p == itemClass
            else p.name.startsWith("com.twitter.ui.dialog.actionsheet")
        }

        // Only if nothing is typed that precisely, widen to Object-parameter methods — the host
        // does declare some dispatch that way. This pass is strictly a fallback because it is
        // broad enough to sit on unrelated call paths.
        if (candidates.isEmpty()) {
            candidates = single.filter { it.parameterTypes[0] == Any::class.java }
        }

        if (candidates.isEmpty()) {
            DiagLog.line("FATAL no item dispatch method on ${controller.name}; clicks inert")
            DiagLog.flushNow()
            XposedBridge.log("XVC: no item dispatch method on ${controller.name}; clicks inert")
            return
        }
        DiagLog.line("hooked ${candidates.size} dispatch method(s)")
        for (m in candidates) {
            m.isAccessible = true
            XposedBridge.hookMethod(m, object : XC_MethodHook() {
                override fun beforeHookedMethod(param: MethodHookParam) {
                    val arg = param.args.getOrNull(0) ?: return
                    if (!isOurEntry(arg)) return
                    DiagLog.line("download entry tapped")
                    runCatching {
                        val sheet = param.thisObject
                        val tweet = tweetOf(sheet)
                        if (tweet == null) {
                            DiagLog.line("ERROR tapped but tweet field not found")
                            return
                        }
                        onDownload(hostContext(sheet), tweet)
                        // Consume it: letting the host continue with an action id it does not
                        // know can put its own dispatch into a default branch.
                        param.result = null
                    }.onFailure {
                        DiagLog.line("ERROR download dispatch failed: $it")
                        XposedBridge.log("XVC: download dispatch failed: $it")
                        Toast.makeText(
                            hostContext(sheet = param.thisObject),
                            moduleResources.failureLabel(hostContext(param.thisObject)),
                            Toast.LENGTH_SHORT,
                        ).show()
                    }
                }
            })
        }
    }

    /** True when [candidate] is the entry this module injected, identified by the sentinel id. */
    private fun isOurEntry(candidate: Any): Boolean {
        val cls = candidate.javaClass
        if (!cls.name.startsWith("com.twitter.ui.dialog.actionsheet")) return false
        for (f in cls.declaredFields) {
            if (Modifier.isStatic(f.modifiers) || f.type != Int::class.javaPrimitiveType) continue
            f.isAccessible = true
            if (runCatching { f.getInt(candidate) }.getOrNull() == sentinelActionId) return true
        }
        return false
    }

    /** The tweet the sheet was opened for. */
    private fun tweetOf(sheet: Any): Any? {
        val wrapper = runCatching { classLoader.loadClass(HostClasses.TWEET_WRAPPER) }.getOrNull()
        if (wrapper != null) {
            HostShapes.uniqueFieldOfType(sheet.javaClass, wrapper)?.let { f ->
                return runCatching { f.get(sheet) }.getOrNull()
            }
        }
        // Fall back to the recorded field name when the wrapper class was renamed.
        return runCatching {
            XposedHelpers.getObjectField(sheet, HostClasses.SHARE_SHEET_TWEET_FIELD)
        }.getOrNull()
    }

    private fun itemsFieldOf(cls: Class<*>) =
        HostShapes.uniqueFieldOfType(cls, List::class.java)
            ?: runCatching {
                cls.getDeclaredField(HostClasses.SHARE_SHEET_ITEMS_FIELD).also {
                    it.isAccessible = true
                }
            }.getOrNull()

    /** A usable context from the host: the sheet's own, or the current activity. */
    private fun hostContext(sheet: Any): Context {
        for (f in sheet.javaClass.declaredFields) {
            if (Modifier.isStatic(f.modifiers)) continue
            f.isAccessible = true
            val v = runCatching { f.get(sheet) }.getOrNull()
            if (v is Activity) return v
            if (v is Context) return v
        }
        return XVideoCatcherModule.appContext
            ?: error("no host context available")
    }
}
