package com.jiesa.xvideocatcher.hook

import android.app.Activity
import android.content.Context
import android.widget.Toast
import de.robv.android.xposed.XC_MethodHook
import de.robv.android.xposed.XposedBridge
import de.robv.android.xposed.XposedHelpers
import java.lang.reflect.Modifier

/**
 * Adds a download entry to X's share sheet, in X's process.
 *
 * How the entry gets there: the sheet controller builds its item list, then calls its show method
 * to display it. Hooking that show method means appending one item to a list that is about to be
 * rendered — no view inflation, no layout inspection, no window of our own. The entry looks native
 * because it *is* native; only its contents come from us.
 *
 * How the click is caught: rather than hooking a click listener (whose class is obfuscated and,
 * unlike the item model, has no stable string anchor left in X 12.13), the injected item is given
 * a sentinel action id. Any item dispatched with that id is ours. That trades a fragile lookup for
 * a value we control.
 *
 * Failure policy: every hook body is wrapped. A throw inside a host UI callback would surface to
 * the user as X crashing, which is a worse outcome than a missing download entry.
 */
internal class ShareSheetInjector(
    private val classLoader: ClassLoader,
    private val moduleResources: ModuleStrings,
    private val onDownload: (Context, Any) -> Unit,
) {

    /**
     * Action id carried by the injected entry.
     *
     * Chosen far outside the host's own id space, which is generated by its resource compiler and
     * lives in low ranges. A collision would mean X's own handler runs for our entry.
     */
    private val sentinelActionId = 0x5EED_0001

    fun install() {
        val controller = runCatching { classLoader.loadClass(HostClasses.SHARE_SHEET_CONTROLLER) }
            .getOrNull()
        if (controller == null) {
            XposedBridge.log("XVC: share sheet controller not found; entry not installed")
            return
        }

        hookSheetShown(controller)
        hookItemDispatch(controller)
    }

    /** Appends the download entry to the item list right before the sheet is shown. */
    private fun hookSheetShown(controller: Class<*>) {
        val showMethods = controller.declaredMethods.filter {
            it.name == HostClasses.SHARE_SHEET_SHOW_METHOD &&
                it.returnType == Void.TYPE &&
                it.parameterTypes.size == 1
        }
        if (showMethods.isEmpty()) {
            XposedBridge.log("XVC: no show method on ${controller.name}; entry not installed")
            return
        }

        for (m in showMethods) {
            XposedBridge.hookMethod(m, object : XC_MethodHook() {
                override fun beforeHookedMethod(param: MethodHookParam) {
                    runCatching { appendEntry(param.thisObject) }
                        .onFailure { XposedBridge.log("XVC: append failed: $it") }
                }
            })
        }
    }

    private fun appendEntry(sheet: Any) {
        val tweet = tweetOf(sheet) ?: return
        // Nothing to download: leave the sheet exactly as X built it rather than showing an
        // entry that can only fail.
        if (TweetMedia.extract(tweet).isEmpty()) return

        val itemsField = itemsFieldOf(sheet.javaClass) ?: return
        val current = itemsField.get(sheet) as? List<*> ?: return
        if (current.any { it != null && isOurEntry(it) }) return

        val entry = buildEntry(sheet) ?: return
        itemsField.set(sheet, current.filterNotNull() + entry)
    }

    /**
     * Builds an item of the host's own item type.
     *
     * The host renders its list by reading fields off these objects, so an entry has to *be* one
     * of them; a look-alike of our own class would be cast-failed or skipped. The 3-arg
     * constructor `(drawableRes, actionId, title)` is the minimal shape that produces a complete
     * row, and it is present in every build examined.
     */
    private fun buildEntry(sheet: Any): Any? {
        val itemClass = runCatching { classLoader.loadClass(HostClasses.ACTION_SHEET_ITEM) }
            .getOrNull() ?: return null

        val ctor = itemClass.declaredConstructors.firstOrNull { c ->
            val p = c.parameterTypes
            p.size == 3 && p[0] == Int::class.javaPrimitiveType &&
                p[1] == Int::class.javaPrimitiveType && p[2] == String::class.java
        } ?: return null
        ctor.isAccessible = true

        val title = moduleResources.downloadLabel(hostContext(sheet))
        // Icon 0 = no icon. Referencing one of X's own drawables would look tidier but ties the
        // entry to a resource id that is regenerated on every host build.
        return runCatching { ctor.newInstance(0, sentinelActionId, title) }.getOrNull()
    }

    /**
     * Watches item dispatch for the sentinel id.
     *
     * Which method receives the chosen item is not knowable by name, so it is selected by
     * signature: takes exactly one argument, and that argument is the host's item type. Hooking
     * every one-argument method instead would put this check on the path of unrelated host calls
     * — measurable on low-end hardware, for no gain.
     */
    private fun hookItemDispatch(controller: Class<*>) {
        val itemClass = runCatching { classLoader.loadClass(HostClasses.ACTION_SHEET_ITEM) }
            .getOrNull()
        val single = controller.declaredMethods.filter {
            !Modifier.isStatic(it.modifiers) && it.parameterTypes.size == 1
        }

        // Prefer methods typed to the item class itself. `isAssignableFrom` is deliberately not
        // used for the primary pass: every class is assignable to Object, so it would match any
        // one-argument method and defeat the narrowing.
        var candidates = single.filter { m ->
            val p = m.parameterTypes[0]
            if (itemClass != null) p == itemClass
            else p.name.startsWith("com.twitter.ui.dialog.actionsheet")
        }

        // Only if nothing is typed that precisely, widen to Object-parameter methods — the host
        // does declare some dispatch that way. This pass is strictly a fallback because it is
        // broad enough to sit on unrelated call paths.
        if (candidates.isEmpty()) {
            candidates = single.filter { it.parameterTypes[0] == Any::class.java }
        }

        if (candidates.isEmpty()) {
            XposedBridge.log("XVC: no item dispatch method on ${controller.name}; clicks inert")
            return
        }
        for (m in candidates) {
            m.isAccessible = true
            XposedBridge.hookMethod(m, object : XC_MethodHook() {
                override fun beforeHookedMethod(param: MethodHookParam) {
                    val arg = param.args.getOrNull(0) ?: return
                    if (!isOurEntry(arg)) return
                    runCatching {
                        val sheet = param.thisObject
                        val tweet = tweetOf(sheet) ?: return
                        onDownload(hostContext(sheet), tweet)
                        // Consume it: letting the host continue with an action id it does not
                        // know can put its own dispatch into a default branch.
                        param.result = null
                    }.onFailure {
                        XposedBridge.log("XVC: download dispatch failed: $it")
                        Toast.makeText(
                            hostContext(sheet = param.thisObject),
                            moduleResources.failureLabel(hostContext(param.thisObject)),
                            Toast.LENGTH_SHORT,
                        ).show()
                    }
                }
            })
        }
    }

    /** True when [candidate] is the entry this module injected, identified by the sentinel id. */
    private fun isOurEntry(candidate: Any): Boolean {
        val cls = candidate.javaClass
        if (!cls.name.startsWith("com.twitter.ui.dialog.actionsheet")) return false
        for (f in cls.declaredFields) {
            if (Modifier.isStatic(f.modifiers) || f.type != Int::class.javaPrimitiveType) continue
            f.isAccessible = true
            if (runCatching { f.getInt(candidate) }.getOrNull() == sentinelActionId) return true
        }
        return false
    }

    /** The tweet the sheet was opened for. */
    private fun tweetOf(sheet: Any): Any? {
        val wrapper = runCatching { classLoader.loadClass(HostClasses.TWEET_WRAPPER) }.getOrNull()
        if (wrapper != null) {
            HostShapes.uniqueFieldOfType(sheet.javaClass, wrapper)?.let { f ->
                return runCatching { f.get(sheet) }.getOrNull()
            }
        }
        // Fall back to the recorded field name when the wrapper class was renamed.
        return runCatching {
            XposedHelpers.getObjectField(sheet, HostClasses.SHARE_SHEET_TWEET_FIELD)
        }.getOrNull()
    }

    private fun itemsFieldOf(cls: Class<*>) =
        HostShapes.uniqueFieldOfType(cls, List::class.java)
            ?: runCatching {
                cls.getDeclaredField(HostClasses.SHARE_SHEET_ITEMS_FIELD).also {
                    it.isAccessible = true
                }
            }.getOrNull()

    /** A usable context from the host: the sheet's own, or the current activity. */
    private fun hostContext(sheet: Any): Context {
        for (f in sheet.javaClass.declaredFields) {
            if (Modifier.isStatic(f.modifiers)) continue
            f.isAccessible = true
            val v = runCatching { f.get(sheet) }.getOrNull()
            if (v is Activity) return v
            if (v is Context) return v
        }
        return XVideoCatcherModule.appContext
            ?: error("no host context available")
    }
}
